USE [master]
GO

/****** Object:  Database [DBBooks]    Script Date: 6/8/2024 9:03:02 AM ******/
CREATE DATABASE [DBBooks]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBBooks', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DBBooks.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBBooks_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DBBooks_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBBooks].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBBooks] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBBooks] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBBooks] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBBooks] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBBooks] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBBooks] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBBooks] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBBooks] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBBooks] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBBooks] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBBooks] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBBooks] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBBooks] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBBooks] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBBooks] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBBooks] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBBooks] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBBooks] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBBooks] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBBooks] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBBooks] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBBooks] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBBooks] SET RECOVERY FULL 
GO

ALTER DATABASE [DBBooks] SET  MULTI_USER 
GO

ALTER DATABASE [DBBooks] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBBooks] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBBooks] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBBooks] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DBBooks] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBBooks] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DBBooks] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DBBooks] SET  READ_WRITE 
GO

